// Emoji categories
export const emojiCategories = [
  'smileys',
  'animals',
  'food',
  'travel',
  'activities',
  'objects',
];

// Emoji data organized by category
export const emojiByCategory = {
  smileys: [
    { emoji: '😀', name: 'grinning face' },
    { emoji: '😃', name: 'grinning face with big eyes' },
    { emoji: '😄', name: 'grinning face with smiling eyes' },
    { emoji: '😁', name: 'beaming face with smiling eyes' },
    { emoji: '😆', name: 'grinning squinting face' },
    { emoji: '😅', name: 'grinning face with sweat' },
    { emoji: '🤣', name: 'rolling on the floor laughing' },
    { emoji: '😂', name: 'face with tears of joy' },
    { emoji: '🙂', name: 'slightly smiling face' },
    { emoji: '🙃', name: 'upside-down face' },
    { emoji: '😉', name: 'winking face' },
    { emoji: '😊', name: 'smiling face with smiling eyes' },
    { emoji: '😇', name: 'smiling face with halo' },
    { emoji: '🥰', name: 'smiling face with hearts' },
    { emoji: '😍', name: 'smiling face with heart-eyes' },
    { emoji: '🤩', name: 'star-struck' },
    { emoji: '😘', name: 'face blowing a kiss' },
    { emoji: '😗', name: 'kissing face' },
    { emoji: '😚', name: 'kissing face with closed eyes' },
    { emoji: '😙', name: 'kissing face with smiling eyes' },
  ],
  animals: [
    { emoji: '🐶', name: 'dog face' },
    { emoji: '🐱', name: 'cat face' },
    { emoji: '🐭', name: 'mouse face' },
    { emoji: '🐹', name: 'hamster' },
    { emoji: '🐰', name: 'rabbit face' },
    { emoji: '🦊', name: 'fox' },
    { emoji: '🐻', name: 'bear' },
    { emoji: '🐼', name: 'panda' },
    { emoji: '🐨', name: 'koala' },
    { emoji: '🐯', name: 'tiger face' },
    { emoji: '🦁', name: 'lion' },
    { emoji: '🐮', name: 'cow face' },
    { emoji: '🐷', name: 'pig face' },
    { emoji: '🐸', name: 'frog' },
    { emoji: '🐵', name: 'monkey face' },
    { emoji: '🐔', name: 'chicken' },
    { emoji: '🐧', name: 'penguin' },
    { emoji: '🐦', name: 'bird' },
    { emoji: '🐤', name: 'baby chick' },
    { emoji: '🦄', name: 'unicorn' },
  ],
  food: [
    { emoji: '🍎', name: 'red apple' },
    { emoji: '🍐', name: 'pear' },
    { emoji: '🍊', name: 'tangerine' },
    { emoji: '🍋', name: 'lemon' },
    { emoji: '🍌', name: 'banana' },
    { emoji: '🍉', name: 'watermelon' },
    { emoji: '🍇', name: 'grapes' },
    { emoji: '🍓', name: 'strawberry' },
    { emoji: '🍑', name: 'peach' },
    { emoji: '🍍', name: 'pineapple' },
    { emoji: '🥥', name: 'coconut' },
    { emoji: '🥝', name: 'kiwi fruit' },
    { emoji: '🍅', name: 'tomato' },
    { emoji: '🥑', name: 'avocado' },
    { emoji: '🍔', name: 'hamburger' },
    { emoji: '🍕', name: 'pizza' },
    { emoji: '🌭', name: 'hot dog' },
    { emoji: '🥪', name: 'sandwich' },
    { emoji: '🌮', name: 'taco' },
    { emoji: '🍩', name: 'doughnut' },
  ],
  travel: [
    { emoji: '🚗', name: 'automobile' },
    { emoji: '🚕', name: 'taxi' },
    { emoji: '🚙', name: 'sport utility vehicle' },
    { emoji: '🚌', name: 'bus' },
    { emoji: '🚎', name: 'trolleybus' },
    { emoji: '🏎', name: 'racing car' },
    { emoji: '🚓', name: 'police car' },
    { emoji: '🚑', name: 'ambulance' },
    { emoji: '🚒', name: 'fire engine' },
    { emoji: '✈️', name: 'airplane' },
    { emoji: '🛩', name: 'small airplane' },
    { emoji: '🚀', name: 'rocket' },
    { emoji: '🛸', name: 'flying saucer' },
    { emoji: '🚁', name: 'helicopter' },
    { emoji: '⛵', name: 'sailboat' },
    { emoji: '🚤', name: 'speedboat' },
    { emoji: '⚓', name: 'anchor' },
    { emoji: '🚲', name: 'bicycle' },
    { emoji: '🛴', name: 'kick scooter' },
    { emoji: '🏍', name: 'motorcycle' },
  ],
  activities: [
    { emoji: '⚽', name: 'soccer ball' },
    { emoji: '🏀', name: 'basketball' },
    { emoji: '🏈', name: 'american football' },
    { emoji: '⚾', name: 'baseball' },
    { emoji: '🎾', name: 'tennis' },
    { emoji: '🏐', name: 'volleyball' },
    { emoji: '🎱', name: 'pool 8 ball' },
    { emoji: '🏓', name: 'ping pong' },
    { emoji: '🏸', name: 'badminton' },
    { emoji: '🥊', name: 'boxing glove' },
    { emoji: '🎯', name: 'direct hit' },
    { emoji: '🎳', name: 'bowling' },
    { emoji: '🏏', name: 'cricket game' },
    { emoji: '🏑', name: 'field hockey' },
    { emoji: '🏒', name: 'ice hockey' },
    { emoji: '🥍', name: 'lacrosse' },
    { emoji: '🏹', name: 'bow and arrow' },
    { emoji: '🎣', name: 'fishing pole' },
    { emoji: '🥋', name: 'martial arts uniform' },
    { emoji: '🎽', name: 'running shirt' },
  ],
  objects: [
    { emoji: '⌚', name: 'watch' },
    { emoji: '📱', name: 'mobile phone' },
    { emoji: '💻', name: 'laptop' },
    { emoji: '⌨️', name: 'keyboard' },
    { emoji: '🖥', name: 'desktop computer' },
    { emoji: '🖨', name: 'printer' },
    { emoji: '🖱', name: 'computer mouse' },
    { emoji: '🖲', name: 'trackball' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '📷', name: 'camera' },
    { emoji: '📹', name: 'video camera' },
    { emoji: '🎥', name: 'movie camera' },
    { emoji: '📞', name: 'telephone receiver' },
    { emoji: '☎️', name: 'telephone' },
    { emoji: '📟', name: 'pager' },
    { emoji: '📠', name: 'fax machine' },
    { emoji: '📺', name: 'television' },
    { emoji: '📻', name: 'radio' },
    { emoji: '🎙', name: 'studio microphone' },
    { emoji: '🎚', name: 'level slider' },
  ],
};

// Flattened list of all emojis for search
export const allEmojis = Object.values(emojiByCategory).flat();
