export const Images = {
  privyLogo: require('@/assets/images/privy-logo-dark.png'),
  appLogo: require('@/assets/icons/adaptive-icon.png'),
  whiteLogo: require('@/assets/images/logo-white.png'),
  bgStars: require('@/assets/images/onboarding/bg-stars.png'),
  bgStars2: require('@/assets/images/onboarding/bg-stars2.png'),
  bgFlare: require('@/assets/images/onboarding/bg-flare.png'),
  bgFlare2: require('@/assets/images/onboarding/bg-flare2.png'),
  bgRocks: require('@/assets/images/onboarding/bg-rocks.png'),
  bgRocksFull: require('@/assets/images/onboarding/bg-rocks-full.png'),
  rocks2: require('@/assets/images/onboarding/rock-2.png'),
  bgRocks3: require('@/assets/images/onboarding/bg-rocks3.png'),
  mascot: require('@/assets/images/mascot.png'),
  mascotWithStar: require('@/assets/images/mascot-with-star.png'),
  mascotError: require('@/assets/images/mascot-error.png'),
  socialDefi: require('@/assets/images/onboarding/social_defi.png'),
  secureWallet: require('@/assets/images/onboarding/secure-wallet.png'),
  tradeWithConfidence: require('@/assets/images/onboarding/trade-with-confidence.png'),
  mascotOnRocks: require('@/assets/images/onboarding/mascot-on-rock.png'),
  arrowBack: require('@/assets/images/arrow-back.png'),
}
